name: m_one
description: "Test project for M-One app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.0
  provider: ^6.1.5+1
  shared_preferences: ^2.5.3
  flutter_mobx: 2.3.0
  mobx: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  mobx_codegen: ^2.7.1


flutter:
  uses-material-design: true
  assets:
    - assets/vectors/logo.svg
